---
- name: Restore the playbook.yml
  hosts: all
  vars_files: vars/vars.yml
  tasks:
    - name: 1) 방화벽 포트 닫기
      firewalld:
        service: "{{ item }}"
        permanent: no
        immediate: no
        state: disabled
      loop:
        - http
        - https

    - name: 2) 웹 서비스 설정 삭제
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 3) 서비스 중지
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - http
        - https

    - name: 4) 패키지 삭제
      yum:
        name: 
          - httpd
          - mod_ssl
          - python3-PyMySQL
          - firewalld
        state: absent